FROM python:3.11-slim

WORKDIR /app
COPY inference/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common/ ./common/
COPY inference/ ./inference/

CMD ["uvicorn", "inference.app.main:app", "--host", "0.0.0.0", "--port", "8080"]